# Section A: Data Structures & Control Structures

## 1. List operations

In [1]:
nlist = [11, 42, 74, 23, 89, 42]     # list creation

In [2]:
nlist.append(100)    # append new element to the last position of list
nlist

[11, 42, 74, 23, 89, 42, 100]

In [3]:
nlist.pop()     # remove last element from list
nlist

[11, 42, 74, 23, 89, 42]

In [4]:
nlist.insert(3, 200)    # insert new element at the specified location
nlist

[11, 42, 74, 200, 23, 89, 42]

In [5]:
nlist.remove(74)     # remove the specified element from the list
nlist

[11, 42, 200, 23, 89, 42]

In [6]:
nlist.extend((42,36))     # extend list with given elements
nlist

[11, 42, 200, 23, 89, 42, 42, 36]

In [7]:
nlist.index(42)     # get the  index of given element

1

In [8]:
c = nlist.count(42)    # count the no of ocuurence of given element
c

3

In [9]:
nlist.sort()     # sort list in ascending order
nlist

[11, 23, 36, 42, 42, 42, 89, 200]

In [10]:
nlist.reverse()     # reverse the list 
nlist

[200, 89, 42, 42, 42, 36, 23, 11]

## 2. tuple operations

In [35]:
students = ('reshal', 'nishal', 'mohit', 'kiran')   # tuple creation
students

('reshal', 'nishal', 'mohit', 'kiran')

In [37]:
students[1] = 'juli'    # trying to update
students

TypeError: 'tuple' object does not support item assignment

## 3. set operations

In [46]:
nset = {34, 87, 82, 100, 65, 58, 87, 107, 100, 99}    # set creation
nset

{34, 58, 65, 82, 87, 99, 100, 107}

## 4. dictionary operations

In [54]:
person = {
    'name' : 'lisha',
    'age'  : 45,
    'city' : 'Mumbai'
}         # dictionary creation
person

{'name': 'lisha', 'age': 45, 'city': 'Mumbai'}

In [58]:
person['age'] = 23      # update value of key 'age'
person

{'name': 'lisha', 'age': 23, 'city': 'Mumbai', 'email': 'lisha@gmail.com'}

In [56]:
person['email'] = 'lisha@gmail.com'     # add new key 'email'
person

{'name': 'lisha', 'age': 45, 'city': 'Mumbai', 'email': 'lisha@gmail.com'}

## 5. eligibility for voting

In [82]:
person_age = int(input("Enter Age:"))    # enter input

if(person_age >= 18):      # check condition
    print("Person is eligible to vote")
else:
    print("Person is not eligible to vote")

Enter Age: 18


Person is eligible to vote


## 6. grade based on the marks

In [108]:
marks = int(input("Enter marks:"))     # enter marks

if marks >= 90:
    print('A grade')
elif marks >= 75:
    print('B grade')
elif marks >= 50:
    print('C grade')
else:
    print('Fail')

Enter marks: 54


C grade


## 7. positive or negative or zero or even

In [117]:
number = int(input("Enter number:"))

if number%2 == 0:
    print('number is even')
    
if number == 0:
    print('Number is zero')
elif number < 0:
    print('Number is negative')
else:
    print('Number is positive')

Enter number: 6


number is even
Number is positive


# Section B: Numpy

## 8. create array

In [136]:
import numpy as np
scalar = np.array(5)
scalar_1D = np.arange(1, 6)   # create 1D array
scalar_1D

array([1, 2, 3, 4, 5])

In [150]:
scalar_2D = np.arange(10, 70, 10)   
scalar_2D.reshape(2, 3)    # create 2D array

array([[10, 20, 30],
       [40, 50, 60]])

## 9. 4x4 Numpy array of random integers 

In [167]:
scalar_4 = np.random.randint(0, 101, size=(4, 4))   # create 4*4 array with random elements
scalar_4

array([[32, 78, 48, 74],
       [30, 20, 27, 65],
       [92, 24, 54, 40],
       [ 8, 11, 83, 50]])

## 10. 2D numpy array of shape

In [179]:
scalar_3 = np.arange(10, 100, 10)
scalar_3 = scalar_3.reshape(3, 3)      # create 3*3 array with 10 to 100 range

import pandas as pd
dframe = pd.DataFrame(scalar_3, columns=['A','B','C'])    # create dataframe with given column name
dframe

A   B   C
0  10  20  30
1  40  50  60
2  70  80  90

# Section C: Exploring Pandas

## DataFrame

In [234]:
employee = {
    'Name' : ['hina', 'mohit', 'anjali', 'priya', 'swati', 'reshu', 'joe', 'shital', 'chetan', 'shital'],
    'Age'  : [89, 65, 16, 73, 19, 46, 25, 20, 45, 20],
    'City' : ['Numbai', 'Hydrabad', 'Kolkata', 'Ambala', 'Delhi', 'Amritsar', 'Puri', 'Vizac', 'Madras', 'Vizac'],
    'Salary':[34000, 45000, 68000, None , 95000, 34000, 62000, 31000, 20000, 31000]
}     # create dictionary

employee_DF = pd.DataFrame(employee)    # create data frame with dictionary
employee_DF

Name  Age      City   Salary
0    hina   89    Numbai  34000.0
1   mohit   65  Hydrabad  45000.0
2  anjali   16   Kolkata  68000.0
3   priya   73    Ambala      NaN
4   swati   19     Delhi  95000.0
5   reshu   46  Amritsar  34000.0
6     joe   25      Puri  62000.0
7  shital   20     Vizac  31000.0
8  chetan   45    Madras  20000.0
9  shital   20     Vizac  31000.0

In [211]:
employee_DF.info()    # get structural information of dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [213]:
employee_DF.describe()    # get summary of data

Age        Salary
count  10.00000      9.000000
mean   46.00000  47777.777778
std    25.69479  23258.212409
min    16.00000  20000.000000
25%    21.25000  34000.000000
50%    45.50000  41000.000000
75%    64.25000  62000.000000
max    89.00000  95000.000000

In [215]:
employee_DF['Name']    # get feture data from Name 

0      hina
1     mohit
2    anjali
3     priya
4     swati
5     reshu
6       joe
7    shital
8    chetan
9     disha
Name: Name, dtype: object

In [217]:
employee_DF['City']

0      Numbai
1    Hydrabad
2     Kolkata
3      Ambala
4       Delhi
5    Amritsar
6        Puri
7       Vizac
8      Madras
9       Kochi
Name: City, dtype: object

In [220]:
employee_DF.drop(columns=['City'])    # drop feature City

Name  Age   Salary
0    hina   89  34000.0
1   mohit   65  45000.0
2  anjali   16  68000.0
3   priya   73      NaN
4   swati   19  95000.0
5   reshu   46  34000.0
6     joe   25  62000.0
7  shital   20  31000.0
8  chetan   45  20000.0
9   disha   62  41000.0

In [226]:
employee_DF.isnull().sum()     # check whether null in data

Name      0
Age       0
City      0
Salary    1
dtype: int64

In [246]:
import warnings
warnings.filterwarnings('ignore')     # filter warnings

mean = employee_DF['Salary'].mean()    # calculate salary average
employee_DF['Salary'].fillna(mean, inplace=True)    # replace null with average value
employee_DF

Name  Age      City        Salary
0    hina   89    Numbai  34000.000000
1   mohit   65  Hydrabad  45000.000000
2  anjali   16   Kolkata  68000.000000
3   priya   73    Ambala  46666.666667
4   swati   19     Delhi  95000.000000
5   reshu   46  Amritsar  34000.000000
6     joe   25      Puri  62000.000000
7  shital   20     Vizac  31000.000000
8  chetan   45    Madras  20000.000000
9  shital   20     Vizac  31000.000000

In [242]:
employee_DF.duplicated().sum()    # check whether any duplicates in data

1

In [244]:
employee_DF.drop_duplicates()     # drop duplicates if any

Name  Age      City   Salary
0    hina   89    Numbai  34000.0
1   mohit   65  Hydrabad  45000.0
2  anjali   16   Kolkata  68000.0
3   priya   73    Ambala      NaN
4   swati   19     Delhi  95000.0
5   reshu   46  Amritsar  34000.0
6     joe   25      Puri  62000.0
7  shital   20     Vizac  31000.0
8  chetan   45    Madras  20000.0